CREATE TABLE Metastore.Temp_Pipeline_Details (
    ADFName NVARCHAR(255),
    pipeline_name NVARCHAR(255),
    pipeline_group_id NVARCHAR(255),
    pipeline_run_id NVARCHAR(255),
    pipeline_trigger_type NVARCHAR(255),
    job_start_date DATETIME,
    source_type NVARCHAR(255),
    db_name NVARCHAR(255),
    schema_name NVARCHAR(255),
    table_name NVARCHAR(255),
    file_name NVARCHAR(255),
    acquisition_strategy NVARCHAR(255),
    merge_strategy NVARCHAR(255),
    data_read BIGINT,
    data_written BIGINT,
    files_read BIGINT,
    files_written BIGINT,
    table_load_status NVARCHAR(255),
    job_end_date DATETIME,
    job_duration INT,
    pipeline_status NVARCHAR(255)
);

CREATE TABLE Metastore.Pipeline_Details (
    ADFName NVARCHAR(255),
    pipeline_name NVARCHAR(255),
    pipeline_group_id NVARCHAR(255),
    pipeline_run_id NVARCHAR(255),
    pipeline_trigger_type NVARCHAR(255),
    job_start_date DATETIME,
    source_type NVARCHAR(255),
    db_name NVARCHAR(255),
    schema_name NVARCHAR(255),
    table_name NVARCHAR(255),
    file_name NVARCHAR(255),
    acquisition_strategy NVARCHAR(255),
    merge_strategy NVARCHAR(255),
    data_read BIGINT,
    data_written BIGINT,
    files_read BIGINT,
    files_written BIGINT,
    table_load_status NVARCHAR(255),
    job_end_date DATETIME,
    job_duration INT,
    pipeline_status NVARCHAR(255)
);
